//Auth
const AUTH_LOADER = 'AUTH_LOADER';

//Debit Card
const SHOW_CARD_NUMBER = 'SHOW_CARD_NUMBER';
const SET_WEEKLY_CARD_LIMIT = 'SET_WEEKLY_CARD_LIMIT';

export {AUTH_LOADER, SHOW_CARD_NUMBER, SET_WEEKLY_CARD_LIMIT};
